### ISSUE TITLE
BUG: Connection fails

### ISSUE THREAD

**Issue by besi** [besi/ida-bell#3]
# Tasks

- [x] Ping according to the set KEEPALIVE time
- [x] Check for MQTT messages non-blockingly if required

See #4 

## Related issues

- [ ] #5
- [ ] #6

# Problem

```
.It's 7:44
gc.collect()
192.168.1.214
connecting to MQTT...
Connection succeeded: True
Connected to dev.b-labs.ch MQTT broker, subscribed to b'timer' topic
{'status': 'hello'}
Ignoring badly formatted or unknown JSON
{'seconds': 180, 'title': 'chickpeas'}
Start the timer 'chickpeas' with 180 seconds
Ringing the bell
Traceback (most recent call last):
  File "main.py", line 82, in <module>
  File "/lib/umqttsimple.py", line 111, in ping
OSError: [Errno 103] ECONNABORTED
```

**Comment by besi** [comment]
It seems that the excessive pinging in the main loop (every second) was too much for the server and hence it aborted the connection.

- [ ] Set timer label and duration and return back to the main loop

See #4

**Comment by besi** [comment]
Error 104 can also occur:

    OSError: [Errno 104] ECONNRESET

**Comment by besi** [comment]
```
Start the timer 'chickpeas' with 1 seconds
Ringing the bell
Erron in main loop: [Errno 103] ECONNABORTED Reconnecting
gc.collect()
connecting to MQTT...
Failed to connect to MQTT broker. Due to error -2 Reconnecting...

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x40100000, len 31212, room 16 
tail 12
chksum 0x88
ho 0 tail 12 room 4
load 0x3ffe8000, len 1060, room 12 
tail 8
chksum 0xd4

```
